export const FEATURES = {
    '_default': {
        'range': [0, Infinity],
        'autoRange': true,
        'color': 'black',
        'type': 'scalar',
        'fftCount': (sr, bs, mfcc) => bs / 2,
    },
    'rms': {
        'title': 'RMS',
        'description': "Root Mean Square, corresponds to loudness",
        'color': 'red',
    },
    'zcr': {
        'title': 'ZCR',
        'description': "Zero Crossing Rate, percussive sounds will have a random ZCR where pitched sounds will be more constant",
        'color': 'teal',
    },
    'energy': {
        'title': 'Energy',
        'description': "Energy, corresponds to loudness",
        'range': (sr, bs, mfcc) => [0, ((bs / 2) - 1)],
        'color': 'orange',
    },
    'amplitudeSpectrum': {
        'title': 'Amplitude Spectrum',
        'description': "Intensity of frequencies in the FFT bins",
        'type': 'fft',
        'autoRange': false,
        'range': [0, 1],
    },
    'powerSpectrum': {
        'title': 'Power Spectrum',
        'description': "Amplitude spectrum, but squared",
        'type': 'fft',
        'autoRange': false,
        'range': [0, 1],
    },
    'spectralCentroid': {
        'title': 'Spectral Centroid',
        'description': "Approximate center of the intensity of frequencies, relative to the FFT bins",
        'range': (sr, bs, mfcc) => [0, bs / 2],
        'color': 'green',
    },
    'spectralFlatness': {
        'title': 'Spectral Flatness',
        'description': "Flatness of the spectrum, noisier signals will have a higher value",
        'range': [0, 1],
        'autoRange': false,
    },
    'spectralSlope': {
        'title': 'Spectral Slope',
        'description': "'Inclination' of the shape of the spectrum",
        'range': [0, 1],
        'autoRange': false,
    },
    'spectralRolloff': {
        'title': 'Spectral Rolloff',
        'description': "The frequency below which 99% of the energy of the spectrum is contained",
        'range': (sr, bs, mfcc) => [0, sr / 2],
        'color': 'red',
    },
    'spectralSpread': {
        'title': 'Spectral Spread',
        'description': "How the frequencies are spread across the spectrum, noisier sounds will be higher, pitched sounds will be lower",
        'range': (sr, bs, mfcc) => [0, bs / 2],
        'color': 'blue',
    },
    'spectralSkewness': {
        'title': 'Spectral Skewness',
        'description': "Whether the spectrum is skewed towards a particular range of values",
        'range': [-Infinity, Infinity],
    },
    'spectralKurtosis': {
        'title': 'Spectral Kurtosis',
        'description': "How 'pointy' the spectrum is, similar ot the inverse of spectral flatness",
        'range': [0, 1],
        'autoRange': false,
    },
    'chroma': {
        'title': 'Chroma',
        'description': "How much of each chromatic pitch class is present in the signal",
        'type': 'pitch',
        'range': [0, 1],
        'color': 'orange',
    },
    'loudness': {
        'title': 'Loudness (Bark Scale)',
        'description': "Loudness of each frequency band in the bark scale",
        'type': 'loudness',
        'range': [0, 1],
        'color': 'green',
    },
    'perceptualSpread': {
        'title': 'Perceptual Spread',
        'description': "Spread of the loudness coefficients, indicates how rich or full a sound is perceived",
        'range': [0, 1],
        'color': 'blue',
    },
    'perceptualSharpness': {
        'title': 'Perceptual Sharpness',
        'description': "How 'sharp' a sound is",
        'range': [0, 1],
        'color': 'red',
    },
    'mfcc': {
        'title': 'MFCC',
        'description': "Intensity of Mel filter bank bands",
        'type': 'fft',
        'autoRange': false,
        'fftCount': (sr, bs, mfcc) => mfcc,
        'range': [0, 1],
    }
};
